services:
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        image: nginx-alpine
        container_name: 'sc_nginx'
        ports:
            - '8080:80'
        volumes:
            - './:/var/www/html'
        networks:
            - internal
    php:
        image: php:fpm-alpine
        container_name: 'sc_php'
        volumes:
            - './:/var/www/html'
        networks:
            - internal
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        container_name: 'sc_redis'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sc-redis:/data'
        networks:
            - internal
networks:
    internal:
        driver: bridge
volumes:
    sc-redis:
        driver: local
